config/routes.rb
Cocform::Application.routes.draw do
    resources :users

   root to: 'staticpages#contactus'

   match '/contactus', to: 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :add, :cell, :city, :email, :fax, :name, :qc, :state, :tel, :wp, :zip

  validates :name, presence: true, length: {maximum: 30 }
  validates :email, presence: true
  validates :qc, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def contactus
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:succes] = "Thank you your interest and God Bless You and your Family!"
      redirect_to @user
  else
    render 'new'

  end
 end  
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title)
  base_title = "Contact CLP"
  if page_title.empty?
    base_title 
  else  
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Please fill in form.</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/staticpages/contactus.html.erb
<div class="center hero-unit">
  <h1>Thank you for being concerned about our Country.</h1>
<p></p>

<%= link_to "Contact Us", contactus_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<div class="row">
<div class="span6 offset3">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :add, "Address" %>
    <%= f.text_field :add %>

    <%= f.label :qc, "Question" %>
    <%= f.text_field :qc %>


    <%= f.submit "Send", class: "btn btn-large btn-primary" %>
  <% end %>
 </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>